# Generated by Django 5.2.17 on 2026-09-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='date_given',
            field=models.DateField(blank=True, null=True),
        ),
    ]
